/*
* This Java source file was generated by the Gradle 'init' task.
*/
package practicaficheros;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.TreeSet;

public class App {

    public TreeSet<Usuario> usuarios = new TreeSet<>();

    public File archivo = new File("./fichero.txt");
    public ObjectInputStream reader;
    public ObjectOutputStream writer;

    public void createUser(String name, String apellidos, int edad, String email) {
        Usuario usuario = new Usuario(name, apellidos, edad, email);
        usuarios.add(usuario);
    }

    public void removeUser(String name) {

        for (Usuario user : usuarios) {
            if (user.getName().equals(name)) {
                usuarios.remove(user);
            }
        }

    }

    public void showUsers() {
        for (Usuario usuario : usuarios) {
            System.out.println(usuario.toString());
        }
    }

    public void MisErrores() {
    }

    public void saveChanges() {
        try {
            if (usuarios != null) {

                writer = new ObjectOutputStream(new FileOutputStream(archivo));
                writer.writeObject(usuarios);
                writer.close();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void verifyFiles() {
        try {
            if (!archivo.exists()) {
                archivo.createNewFile();
            }
            reader = new ObjectInputStream(new FileInputStream(archivo));
            Object objectToCast = reader.readObject();
            if (objectToCast instanceof TreeSet) {
                usuarios = (TreeSet<Usuario>) objectToCast;
            } else {
                throw new IOException("Data file is not Treeset");
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public boolean check() {

        return true;
    }

    public static void main(String[] args) {
        App menu = new App();
        menu.verifyFiles();
        menu.showUsers();
        menu.saveChanges();
    }
}
